{% set name = "oda-api" %}
{% set version = "1.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oda_api-{{ version }}.tar.gz
  sha256: 301760af3c0cef47a299c60c19f66f48045e0aa5642aebc7fa8e3113ff435143

build:
  noarch: python
  entry_points:
    - oda-api = oda_api.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - future
    - astropy >=3.2
    - json_tricks
    - matplotlib-base
    - numpy
    - jsonschema
    - pyjwt
    - astroquery
    - scipy
    - rdflib
    - black

test:
  imports:
    - oda_api
  commands:
    - pip check
    - oda-api --help
    - pytest tests/test_data_products.py -k "not test_new_binary_product"
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/oda-hub/oda_api
  summary: API plugin for MMODA astronomical online data analysis
  description: |
    MMODA (https://www.astro.unige.ch/mmoda/) is an open-source platform for building and sharing web-based astronomical data analysis workflows.
    ODA-API python package provides programmatic access to the platform.
    ODA-API also contains class hierarchy representing common of astronomical data types, described in https://odahub.io/ontology/

  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  doc_url: https://oda-api.readthedocs.io
  dev_url: https://github.com/oda-hub/oda_api

extra:
  recipe-maintainers:
    - volodymyrss
